context.modules = [
    {
        name = libpipewire-module-loopback
        args = {
            node.description = "Yukkuri Virtual Mic"
            capture.props = {
                node.name = "yukkuri_sink"
                media.class = "Audio/Sink"
                audio.position = [ FL FR ]
            }
            playback.props = {
                node.name = "yukkuri_source"
                media.class = "Audio/Source"
                audio.position = [ FL FR ]
            }
        }
    }
]
